sudo: required
services: 
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker build -t higaguin/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true higaguin/react-test npm test

after_success:
  - docker build -t higaguin/axolotl-client ./client
  - docker build -t higaguin/axolotl-nginx ./nginx
  - docker build -t higaguin/axolotl-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - echo "$HEROKU_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker tag higaguin/axolotl-client registry.heroku.com/$HEROKU_APP_CLIENT_NAME/web
  - docker tag higaguin/axolotl-server registry.heroku.com/$HEROKU_APP_SERVER_NAME/web
  - docker tag higaguin/axolotl-nginx registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push higaguin/axolotl-client;
    docker push registry.heroku.com/$HEROKU_APP_CLIENT_NAME/web;
    heroku container:release web --app $HEROKU_APP_CLIENT_NAME;
    docker push higaguin/axolotl-server;
    docker push registry.heroku.com/$HEROKU_APP_SERVER_NAME/web;
    docker push higaguin/axolotl-nginx;
    docker push registry.heroku.com/$HEROKU_APP/web;
  on:
    branch: master