version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
  api:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    # command: >
    #   sh -c "node_modules/.bin/sequelize db:migrate:undo:all &&
    #          node_modules/.bin/sequelize db:migrate &&
    #          node_modules/.bin/sequelize db:seed:all &&
    #          npm run dev"
    depends_on: 
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on: 
      - api
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on: 
      - client